// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emzrdczvfshmyidugbut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtenJkY3p2ZnNobXlpZHVnYnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTI1MDcsImV4cCI6MjA2MjAyODUwN30.P9904bBGqobe0dyVR2fWziKdNXY-FVCd7XGCNcKDKAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);